/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './hooks/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Landing-aligned emerald system (black + green)
        brand: {
          50:  '#03251A',
          100: '#064E3B',
          200: '#047857',
          400: '#34D399',
          600: '#10B981',
          800: '#A7F3D0',
          900: '#D1FAE5',
        },
        // Landing-aligned zinc neutrals for dashboard shell
        surface: {
          0:   '#000000',
          50:  '#09090B',
          100: '#111113',
          200: '#18181B',
          300: '#27272A',
          400: '#3F3F46',
          500: '#71717A',
          600: '#A1A1AA',
          700: '#D4D4D8',
          800: '#E4E4E7',
          900: '#F4F4F5',
        },
        // Semantic
        danger:  { bg: '#FCEBEB', border: '#F09595', text: '#791F1F' },
        warning: {
          bg: '#FAEEDA',
          border: '#EF9F27',
          text: '#633806',
          500: 'rgb(var(--warning-500) / <alpha-value>)',
          DEFAULT: 'rgb(var(--warning-500) / <alpha-value>)',
        },
        info:    { bg: '#E6F1FB', border: '#85B7EB', text: '#0C447C' },
        purple:  { bg: '#EEEDFE', border: '#AFA9EC', text: '#3C3489' },
        primary: {
          500: 'rgb(var(--primary-500) / <alpha-value>)',
          600: 'rgb(var(--primary-600) / <alpha-value>)',
          DEFAULT: 'rgb(var(--primary-500) / <alpha-value>)',
        },
        secondary: {
          500: 'rgb(var(--secondary-500) / <alpha-value>)',
          600: 'rgb(var(--secondary-600) / <alpha-value>)',
          accent: 'rgb(var(--secondary-accent) / <alpha-value>)',
          DEFAULT: 'rgb(var(--secondary-500) / <alpha-value>)',
        },
        neutral: {
          0: 'rgb(var(--neutral-0) / <alpha-value>)',
          50: 'rgb(var(--neutral-50) / <alpha-value>)',
          300: 'rgb(var(--neutral-300) / <alpha-value>)',
          400: 'rgb(var(--neutral-400) / <alpha-value>)',
          500: 'rgb(var(--neutral-500) / <alpha-value>)',
          600: 'rgb(var(--neutral-600) / <alpha-value>)',
          700: 'rgb(var(--neutral-700) / <alpha-value>)',
          800: 'rgb(var(--neutral-800) / <alpha-value>)',
          900: 'rgb(var(--neutral-900) / <alpha-value>)',
          1000: 'rgb(var(--neutral-1000) / <alpha-value>)',
        },
        success: {
          500: 'rgb(var(--success-500) / <alpha-value>)',
          DEFAULT: 'rgb(var(--success-500) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'Georgia', 'ui-serif', 'serif'],
        mono: ['var(--font-geist-mono)', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        xs:    ['12px', { lineHeight: '16px' }],
        sm:    ['13px', { lineHeight: '20px' }],
        base:  ['14px', { lineHeight: '22px' }],
        md:    ['15px', { lineHeight: '24px' }],
        lg:    ['16px', { lineHeight: '26px' }],
        xl:    ['18px', { lineHeight: '28px' }],
        '2xl': ['22px', { lineHeight: '32px' }],
        '3xl': ['28px', { lineHeight: '36px' }],
      },
      borderRadius: {
        sm:  '6px',
        md:  '8px',
        lg:  '12px',
        xl:  '16px',
        '2xl': '20px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)',
        focus: '0 0 0 3px rgba(52,211,153,0.25)',
      },
      animation: {
        'fade-in':  'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.25s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'shimmer':  'shimmer 1.8s linear infinite',
        'spin-slow': 'spin 2s linear infinite',
        'landing-rise': 'landingRise 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'landing-rise-delayed': 'landingRise 0.7s cubic-bezier(0.22, 1, 0.36, 1) 0.1s forwards',
        'landing-rise-delayed-2': 'landingRise 0.7s cubic-bezier(0.22, 1, 0.36, 1) 0.2s forwards',
      },
      keyframes: {
        landingRise: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn:  { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        pulseSoft: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
        shimmer: { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
      },
    },
  },
  plugins: [],
}
